name: Docker Image CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  publish-tts-web-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tts-web Docker image
        run: |
          docker build . --tag ghcr.io/santhoshtr/tts-web:latest
          docker push ghcr.io/santhoshtr/tts-web:latest
